apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: eduresearch

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - services.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: eduresearch
  app.kubernetes.io/managed-by: kustomize
