apiVersion: v1
kind: Service
metadata:
  name: eduresearch-backend
  namespace: eduresearch
spec:
  selector:
    app: eduresearch-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: eduresearch-frontend
  namespace: eduresearch
spec:
  selector:
    app: eduresearch-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
